# Generated by Django 3.0.5 on 2020-04-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregister',
            options={'ordering': ['-created'], 'verbose_name': 'Event Register', 'verbose_name_plural': 'Event Register'},
        ),
    ]
